fix encoding name in order to fix build error with Ruby 2.2.0-rc1
The behavior of ripper which is used by detecting file dependency is changed at Ruby 2.2.0-rc1.
If specify "undecided" in encoding name, ripper will raise ArgumentError like following.

$ bundle exec rake
     Build ./build/iPhoneSimulator-7.0-Development
     Build vendor/Bolts.framework
     Build vendor/Parse.framework
rake aborted!
ArgumentError: unknown encoding name: undecided